### ISSUE TITLE
is possible to build this as dynamic mod for nginx?

### ISSUE THREAD

**Issue by theraw** [auto-ssl/lua-resty-auto-ssl#102]
hello,

As i wasn't able to find anything about this in readme.md and i don't know how OpenResty works as i haven't use it before i'm asking if is possible to build this and use as dynamic module directly for Nginx?!

my nginx version is `nginx/1.13.4 (nginx-plus-r13)`

Thanks.

**Comment by chipitsine** [comment]
@theraw , you are right, if you do not understand it, it is a documentation issue.

as for your particular case, you need nginx-plus with Lua module. openresty is built on top of nginx-lua.
so, dynamic module is nginx-lua (I guess, there's such module provided with nginx plus)

**Comment by theraw** [comment]
yes right there is "nginx-plus-module-lua" 

so there is nothing to build? https://github.com/GUI/lua-resty-auto-ssl is just something like a "helper" who does the needed work?

**Comment by chipitsine** [comment]
It seems, I was wrong, I never tried it on stock nginx. There's special patch for nginx core.
