### ISSUE TITLE
Redis host url is being modified by code

### ISSUE THREAD

**Issue by sherryt400** [auto-ssl/lua-resty-auto-ssl#214]
```
    auto_ssl:set("redis", {
      host = "redis.private-services.",
      port = 6379,
      db = 1
    })
```
`redis.private-services.` is my redis host but in log i am getting
`failed to obtain lock: redis.private-services could not be resolved (3: Host not found)`
As you can see dot (.) from the end of host has been removed that's why Host not found error is generating.

**Comment by aviatrix** [comment]
Can you confirm that the issue is not at nginx level DNS resolver, because AFAIK auto-ssl uses nginx`s dns resolver. So if nginx doens't handle FQDN, auto-ssl can't either (AFAIK). 
Also, have you configured the DNS resolver at NGINX level ?

**Comment by sherryt400** [comment]
I am using AWS Route 53 private hosted zones
I am using `redis.private-services.` host endpoint everywhere in my code inside my VPC and i am not having any problem. I am using ubuntu ec2 instance for OpenResty which is also inside the same VPC so If I use real endpoint it works fine. If I provide above-mentioned endpoint, ending dot is being removed by lua-resty

**Comment by sherryt400** [comment]
yes I have added DNS resolver in .conf file 
`resolver 10.0.0.2 8.8.8.8 [::1]:5353 valid=30s ipv6=off;`
here 10.0.0.2 is DNS resolver of aws VPC

**Comment by sherryt400** [comment]
https://serverfault.com/questions/843138/why-does-nginx-ignore-trailing-dots-in-the-host-header
That's a problem from nginx side
Thanks
