### ISSUE TITLE
"certificate is not standards compliant" error

### ISSUE THREAD

**Issue by brendon** [auto-ssl/lua-resty-auto-ssl#215]
I've just updated to 0.13.1 because of warnings about Acme 1 being turned off. Unfortunately I've come up against a bug when automatically creating new certificates. When first accessing the address, the browser seems to wait a while, then pops up a certificate warning:

<img width="699" alt="Screen Shot 2020-01-20 at 1 06 45 PM" src="https://user-images.githubusercontent.com/81871/72691091-8539c180-3b87-11ea-949d-7eb597c584af.png">

It looks like both the issued certificate and the Authority certificate are received as invalid.

The strange thing is that if I refresh the page in half a minute or so the certificates are downloaded as valid. I suspect a timeout issue is happening.

Do you have any advice on how to get around this? I wonder if it will also be a transient problem for the user who triggers a certificate renewal too (for our existing sites).

There are no errors in the nginx logs.

I upgraded to the latest openresty at the same time (1.15.8.2).

**Comment by GUI** [comment]
@brendon: Hm, I haven't seen this before. I've found some references to this error related to new certificate requirements in Macs: https://support.apple.com/en-us/HT210176 However, off hand, I'm not sure why any of those wouldn't be met by default, and the timing aspect of this is certainly curious. The timing makes me wonder about some other things: Is the clock on your system properly synchronized? You could check https://www.timeanddate.com/ or https://time.is/ to see if your system clock matches the true time. This is a wild guess, but I'm wondering if this error could occur if your system clock is sufficiently behind the real time, so when the certificate is first registered, your system clock thinks it's still behind the "Not Valid Before" time. I'd expect a more obvious error if this was the issue, but that's one random possibility that comes to mind.

**Comment by brendon** [comment]
Hi @GUI, that's a good hunch. Unfortunately the time is correct on the server and the local machine. I did another test today and get something slightly different (though Safari still complains). Strangely the cert shows as valid by the time Safari goes to show it to us. Refreshing allows the site to load correctly:

![Screen Shot 2020-02-21 at 9 06 47 AM](https://user-images.githubusercontent.com/81871/74974240-bf012f00-5489-11ea-905e-8df48cce08e5.png)
![Screen Shot 2020-02-21 at 9 06 55 AM](https://user-images.githubusercontent.com/81871/74974250-c32d4c80-5489-11ea-9e33-7d2fa81cb59f.png)
![Screen Shot 2020-02-21 at 9 07 05 AM](https://user-images.githubusercontent.com/81871/74974264-c88a9700-5489-11ea-93d4-de77ee960015.png)

Certainly unusual :)

**Comment by gjongenelen** [comment]
What is the validity of your fallback certificate? I got this error once when the certificates validity was beyond 825 days

**Comment by brendon** [comment]
Ah that's interesting :) I just renewed the fallback certificate and reloaded Nginx but it didn't work. Then I thought "eh, what the hell" and tried restarting Nginx instead and it appears to be working now. Pretty strange! I'll close this for now, but let me know if you want me to look further into it.
