### ISSUE TITLE
Challenges are not deleted from storage after unsuccessful verification or cert expire

### ISSUE THREAD

**Issue by mitridatik** [auto-ssl/lua-resty-auto-ssl#224]
Version: 0.13.1 Redis is used as storage. 

Challenges are left in redis after unsuccessful verification. When domain cert expires it is deleted but challenges are not. So challenges are just accumulating.

Domain files are also left after unsuccessful verification while not needed. Don't know if they are deleted as well when domain cert expires.

**Comment by gohai** [comment]
Those should be addressed in
https://github.com/auto-ssl/lua-resty-auto-ssl/pull/206
https://github.com/auto-ssl/lua-resty-auto-ssl/pull/209

**Comment by mitridatik** [comment]
Ok, great, thank you!
